### ISSUE TITLE
Collapse button is hidden underneath "Not Reviewed" / "Reviewed" status indicator and therefore hard to click

### ISSUE THREAD

**Issue by gijsk** [bwinton/reviewboard-collapse#1]
<img width="114" alt="screen shot 2016-04-20 at 10 01 06" src="https://cloud.githubusercontent.com/assets/375983/14669024/dcb40600-06de-11e6-86ca-ddbe51ee9e15.png">

I have to mark items as "Reviewed" first, before I can actually reach the indicator, and when I do that I still only have a sliver of a button to click on. :-(

**Comment by bwinton** [comment]
Wanna submit a pull request to move the button down a little?  :wink:

**Comment by gijsk** [comment]
Hmm, yeah, I wondered if that was too evil. Like, where do the reviewed / not reviewed things come from and/or why isn't everyone having this problem ?

**Comment by gijsk** [comment]
That is, if those buttons are not there, shifting it down is probably wrong?

I also noticed when I investigated a little bit that I'm seeing 2 buttons in every container (on top of each other, obviously) - not sure why.

**Comment by gijsk** [comment]
I think they got rid of the "reviewed" / "not reviewed" button... so closing this? :-)

**Comment by gijsk** [comment]
annnnd they put it back. Sigh.

**Comment by gijsk** [comment]
I put up a PR in #2 .
